name: Deploy Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H sbryan.studio >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: Deploy via SSH
        run: |
          ssh -i ~/.ssh/id_ed25519 bryan@sbryan.studio << 'EOF'
            export PATH=$HOME/.local/share/pnpm:$PATH
            cd /home/bryan/projets/spanishfutsal-frontend
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart spanish-front
          EOF
